"""Change adu.text to MEDIUMTEXT

Revision ID: 16583ce3e4f8
Revises: 5f0ca59f3ade
Create Date: 2025-05-01 20:29:03.366161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16583ce3e4f8'
down_revision: Union[str, None] = '5f0ca59f3ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adu', 'text',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adu', 'text',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
